claims_ops:
  target: duckdb

  outputs:
    duckdb:
      type: duckdb
      path: target/claims_ops.duckdb
      schema: main
      threads: 4

    ci:
      type: duckdb
      path: target/ci.duckdb
      schema: main
      threads: 4