apiVersion: v1
kind: Service
metadata:
  name: findoc-analyzer
  namespace: findoc-analyzer
spec:
  type: ClusterIP
  selector:
    app: findoc-analyzer
  ports:
    - name: http
      port: 80
      targetPort: http

---
apiVersion: v1
kind: Service
metadata:
  name: findoc-analyzer-lb
  namespace: findoc-analyzer
spec:
  type: LoadBalancer
  selector:
    app: findoc-analyzer
  ports:
    - name: http
      port: 80
      targetPort: http
